### ISSUE TITLE
type' attribute is escaping "/"

### ISSUE THREAD

**Issue by coot** [bodil/purescript-smolder#25]
If I add `script ! type "application/sjon" $ text ""` this is rendered (to string) as
`<script type="application&#x2F;json></script>`. It seems that all attributes are escaped `href` to which makes it useless.  

 The type of `String` could be substituted wtih `Either String String` with `Left` being unsafe (not escaped) and `Right` safe string (escaped when processes).

**Comment by ejconlon** [comment]
This appears to be a problem with the `type` attribute in `link` tags as well.  (I believe a new pattern needs to be added to `isMIMEAttr`.) . Is it possible to work around this with an "unescaped" or "raw" attribute combinator?
