### ISSUE TITLE
Usage with DOM Renderer

### ISSUE THREAD

**Issue by JamieWohletz** [bodil/purescript-smolder#27]
First of all, **thank you for all your hard work**! Without you, the purescript package library would be woefully tiny. 

I have a question about the correct way to use purescript-smolder with the [DOM renderer](https://pursuit.purescript.org/packages/purescript-smolder-dom/1.1.0/docs/Text.Smolder.Renderer.DOM#v:render).

In the README for this repository, this example is provided for adding a click listener to a button: 
```
doc = div ! className "not-a-form" $ do
  button #! on "click" (\event → log "boom!") $ text "boom"
```

When I check the type of this in the REPL, it resolves to:
```
forall t11 t12.                     
  MarkupM                           
    (t11                            
     -> Eff                         
          ( console :: CONSOLE      
          | t12                     
          )                         
          Unit                      
    )                               
    Unit
```

The type for `render` is `render :: forall eff. Element -> Markup (E eff) -> Eff (dom :: DOM | eff) Unit`, so when I go to render like this: `render wrapper doc` (where "wrapper" is an Element), I get this compiler error:

```
  Could not match type

    Function t1

  with type

    EventListener


while trying to match type t1
                           -> Eff
                                ( console :: CONSOLE
                                | t2
                                )
                                Unit
  with type EventListener
              ( dom :: DOM
              | t0
              )
while checking that expression doc
  has type MarkupM
             (EventListener
                ( dom :: DOM
                | t0
                )
             )
             Unit
in value declaration renderControls

where t0 is an unknown type
      t2 is an unknown type
      t1 is an unknown type
```

And I'm positively stumped. I'm still pretty new to purescript so reading an error like this is very difficult for me. I'm sorry to submit an issue here since I'm probably doing something wrong, but I didn't know where else to get help. 

Thanks!

**Comment by bodil** [comment]
Going from the type error, I think you're trying to pass a plain function as an event handler, where `purescript-dom` expects a wrapped `EventListener` type - which is just a newtype around a function which looks exactly like what you've got, but you do still need to wrap it. See https://pursuit.purescript.org/packages/purescript-dom/4.5.0/docs/DOM.Event.EventTarget#v:eventListener

**Comment by JamieWohletz** [comment]
It worked! Awesome, thank you! By the way, where are some good places to go for purescript help in the future?

**Comment by bodil** [comment]
I'd recommend the mailing list or the irc channel, at least for core PS issues.

**Comment by JamieWohletz** [comment]
Thanks!
