### ISSUE TITLE
Leverage purescript-virtual-dom from contrib

### ISSUE THREAD

**Issue by fluffynukeit** [bodil/purescript-smolder#5]
It would be useful for smolder to use the virtual dom package `purescript-virtual-dom` in `purescript-contrib` instead of rolling its own bindings.  This would, for instance, standardized the `VTree` type across the libraries, and possibly other functionality.

See comment from @garyb [here](https://github.com/purescript-contrib/purescript-react/issues/25#issuecomment-66652428) regarding smolder and virtual-dom.

**Comment by bodil** [comment]
I took the vdom code out of the core lib, so I guess this one's resolved too.
