### ISSUE TITLE
Remove dependency on NPM

### ISSUE THREAD

**Issue by Fresheyeball** [bodil/purescript-smolder#8]
I would be nice if smolder worked on the browser side.

**Comment by garyb** [comment]
http://browserify.org/ :)

**Comment by Fresheyeball** [comment]
Browserify is not the answer I'm looking for. Yes it technically can be run in the browser, but only by tightly coupling this lib to a build process. I'd like to be able to use Smolder like any other purescript lib, direct from bower, unless its doing something node.js specific.

**Comment by Fresheyeball** [comment]
So it looks like the only issue here is the `Text.Smolder.Renderer.VTree` module. But no other part of Smolder depends on this module. @bodil  would you consider moving this module to another lib?

**Comment by garyb** [comment]
Ah, it seems there is a `dist` package of `virtual-dom` now - I was going to ask how you were including that in your project, as that did pretty much require `npm` & `browserify` to be of use at one point.

If you only need `VTree` why don't you use [`purescript-virtual-dom`](https://github.com/purescript-contrib/purescript-virtual-dom) instead?

**Comment by garyb** [comment]
Ah, sorry, read that the wrong way round. I see, you don't want `virtual-dom` at all.

**Comment by Fresheyeball** [comment]
Well, `virtual-dom` might make sense, its just not having `require` statements in ffi code when the package is not node.js specific.

**Comment by bodil** [comment]
See https://github.com/bodil/purescript-smolder/issues/5#issuecomment-66924404 - removing the vdom code is the intention. If you don't use it, though, does it still make the rest of it unable to run in a browser?

**Comment by Fresheyeball** [comment]
Well it depends... it should be able to run with dead code elimination. But if the `require` statement shows up in the output for the browser the js eval errors out.

**Comment by bodil** [comment]
Ah, yes, I was thinking if you don't require that module it won't be in the output either, but I guess that's only true with CommonJS. :)

**Comment by bodil** [comment]
Dealt with in 0feecc8e - hopefully didn't break anything, I just deleted the file without testing. I'll cut a release later.

**Comment by Fresheyeball** [comment]
Thanks @bodil, I'm going to delete it from my `bower_components` for now until the release is ready.

**Comment by bodil** [comment]
Bumped and released.

**Comment by Fresheyeball** [comment]
:+1:  your rock @bodil !
